GET http://localhost:8083/video/

###
POST http://localhost:8083/video/
Content-Type: application/json

{
    "videoId":3,
    "title":"Java Springboot",
    "duration":"1:15:27",
    "uploadedBy":"Ram",
    "views":"27K",
    "dateOfUpload":"27-05-2024",
    "playlistId":3
}

###
DELETE http://localhost:8083/video/3

###
PUT http://localhost:8083/video/
Content-Type: application/json

{
    "videoId":2,
    "title":"Java Springboot",
    "duration":"1:15:27",
    "uploadedBy":"Ram",
    "views":"27K",
    "dateOfUpload":"27-05-2024",
    "playlistId":2
}

###
GET http://localhost:8083/video/1

###
GET http://localhost:8083/video/byPlaylist/1